Fix:issue#1216 allow the search filters to be cleared or reset to the default
cockpit-project/cockpit-podman pull request #1292
Opened 2023-05-18 13:50 UTC by shubhit7

Fixes #1216 

- Change owner filter, from `FormSelect` to `Select` next component of patternfly alpha release. Old `Select` has been deprecated.
- Change the search field beside owner filter, from `TextInput` to `SearchInput`.

2023-05-18 14:40 UTC, shubhit7 commented
I figured out how we can use deprecated `Select`.
@KKoukiou Shall we use deprecated `Select` or `Select` Next ?

2023-05-19 06:49 UTC, KKoukiou commented
> I figured out how we can use deprecated `Select`. @KKoukiou Shall we use deprecated `Select` or `Select` Next ?

Either of the two works for now. Tending towards the deprecated one, so that we can move all Selects at once  to the new.

2023-05-24 07:05 UTC, KKoukiou requested changes
I am happy with the search input adoption - but totally disagree with adopting the typeahead for the system/user filter. Logs page uses the typeahead in a case where there are hunderds of select options, not 3 like here. 
I know it's suggested in https://github.com/cockpit-project/cockpit-podman/issues/1216#issue-1601474369 but it's just not correct design wise..

Please undo the select part, and keep the SearchInput. Let's also add a test for the new functionality and it's good to go.

2023-05-24 07:05 UTC, KKoukiou commented on src/ContainerHeader.jsx
> +
Newline inside object should be removed.

2023-06-06 09:03 UTC, cockpituous commented on src/ContainerHeader.jsx
> +                                   onClear={() => handleFilterChanged('')} />
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1292-20230606-085317-ba80941c-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-22 18:40 UTC, shubhit7 commented
> PR looks good from my side but the tests fail everywhere, it looks like you will need to adjust how test for the value of the search input:
> 
> ```
> wait_js_cond(ph_has_val("#containers-filter","pod-1")): Uncaught (in promise) Error: #containers-filter does not have a value
> ```

You are right, using the SearchInput component changes the structure of dom elements compared to using simple TextInput component. Now the input box will be accessible by selector `"#containers-filter input"`.

`wait_js_cond(ph_has_val("#containers-filter input","pod-1")) ` should not throw any exception. I am not able to get hands on test suite setup.

2025-01-19 07:21 UTC, martinpitt commented
Continuing in #1968

2025-01-19 07:21 UTC, closed without merging