Add manifest conditions
cockpit-project/cockpit-podman pull request #1305
Opened 2023-06-14 15:04 UTC by jelly

Check for the existence of the podman.socket for the Cockpit client scenario.

2023-06-15 09:14 UTC, martinpitt commented
[this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1305-20230615-081639-f2852b4c-rhel-8-9/log.html#19) looks relevant. The rest look like unrelated flakes.

2023-06-15 10:11 UTC, jelly commented
> [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1305-20230615-081639-f2852b4c-rhel-8-9/log.html#19) looks relevant. The rest look like unrelated flakes.

Well yeah, `systemctl daemon-reload` needs to be run /o\

2023-06-15 11:25 UTC, martinpitt commented
@jelly Because TF's rawhide image is still a bit older, the new 294 version isn't in that yet?

2023-06-15 14:01 UTC, martinpitt requested changes
Hmm, it still failed on most OSes, although the logic looks okay to me :cry:

2023-06-15 15:46 UTC, martinpitt approved these changes
Cheers!

2023-06-15 19:45 UTC, martinpitt commented
[really stubborn](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1305-20230615-192148-d67bf2c7-ubuntu-2204/log.html)!

2023-06-16 05:50 UTC, martinpitt commented
[This](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1305-20230616-053112-d67bf2c7-ubuntu-2204/log.html#27) is really stubborn, I already retried like 5 times. @jelly this smells a lot like https://github.com/cockpit-project/bots/issues/4829 , let's just copy the naughty?

2023-06-16 05:53 UTC, martinpitt commented
I filed https://github.com/cockpit-project/bots/pull/4884 to fix this. Landing this PR as it's unrelated.

2023-06-16 05:53 UTC, merged