package.json: bump esbuild
cockpit-project/cockpit-podman pull request #1381
Opened 2023-08-21 11:16 UTC by AdamMajer

Bump dependency of esbuild to fix a dependency issue during install

npm i --package-lock-only
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree npm ERR!
npm ERR! While resolving: podman@undefined
npm ERR! Found: esbuild@0.18.20
npm ERR! node_modules/esbuild
npm ERR! dev esbuild@"^0.18.14" from the root project npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"^0.19.1" from esbuild-sass-plugin@2.12.0 npm ERR! node_modules/esbuild-sass-plugin
npm ERR! dev esbuild-sass-plugin@"^2.10.0" from the root project npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Closes: #1380

2023-08-21 11:36 UTC, tomasmatus requested changes

2023-08-21 12:43 UTC, AdamMajer commented
I'm not sure how to update this since the node-cache repository is inaccessible.

2023-08-22 09:24 UTC, jelly commented
> I'm not sure how to update this since the node-cache repository is inaccessible.

Yes, this is contributors only. We'll handle it :)

2023-08-22 09:24 UTC, jelly approved these changes

2023-08-22 09:25 UTC, merged