Support the updates-testing scenario in `test/run`
cockpit-project/cockpit-podman pull request #1393
Opened 2023-09-05 07:45 UTC by jelly

Slowly we are getting there, sorry I forgot that we have a custom `test/run` per project while I should have known and noted in my PR original Cockpit PR.

2023-09-05 07:59 UTC, jelly commented
Hmm I do see `dnf -y update` but I don't see any updates output https://cockpit-logs.us-east-1.linodeobjects.com/pull-1393-20230905-074549-c169a45a-fedora-38-updates-testing/log

2023-09-05 08:32 UTC, martinpitt commented
It feels a little weird to me to do it that way -- When accidentally not dropping --fresh, it would silently succeed. Makefile already handles the pybridge scenario, why not updates-testing as well? That's easier to reproduce locally as a developer as well.

That said, fine to land of course -- so far the running test looks good.

2023-09-05 08:45 UTC, jelly commented
> It feels a little weird to me to do it that way -- When accidentally not dropping --fresh, it would silently succeed. Makefile already handles the pybridge scenario, why not updates-testing as well? That's easier to reproduce locally as a developer as well.
> 
> That said, fine to land of course -- so far the running test looks good.

Yeah feels a bit hackish right? I'm happy to improve this, I tried using `VM_CUSTOMIZE_FLAGS but for some reason that seems to clash with the normal `image-customize`. I'm happy to wait till I have better internet so I can debug this better.

2023-09-05 08:52 UTC, martinpitt commented
I meant, just do this *entirely* in Makefile, just like it handles /pybridge.

2023-09-05 09:23 UTC, jelly commented
> I meant, just do this _entirely_ in Makefile, just like it handles /pybridge.

Sure, but what I am wondering is if this requires us to run `vm-customize` twice or can it be done with one invocation?

2023-09-05 13:38 UTC, martinpitt commented
One is enough, you can string arbitrarily many options together. It's a trade-off between being faster, and being able to run parts of your setup with `--no-network`.

2023-09-06 09:07 UTC, martinpitt requested changes
Looks nice! just one detail

2023-09-06 09:07 UTC, martinpitt commented on Makefile
>  VM_CUSTOMIZE_FLAGS = --install $(COCKPIT_WHEEL)
This now should also get `--no-network`

2023-09-06 09:40 UTC, jelly commented
We never tested centos-8-stream so this is expected to fail

2023-09-06 11:44 UTC, martinpitt commented
@jelly please add a second commit to drop the pybridge scenario. Cheers!

2023-09-06 13:34 UTC, martinpitt approved these changes
Cheers!

2023-09-06 14:00 UTC, merged