feat: allow deleting intermediate images
cockpit-project/cockpit-podman pull request #1406
Opened 2023-09-13 17:42 UTC by subhoghoshX

fixes #1320

2023-09-14 14:47 UTC, jelly commented
This feels like an anti feature, intermediate images are likely used by something and can't be removed usually like:

```
[jelle@t14s][~]%podman rmi cab04ad2eb6d
Error: image used by 2f0a0f7f5c4ff8f09dd7efcf214b56238fa9bbe35d20e30b291580e6dc66bb61: image is in use by a container: consider listing external containers and force-removing image
```

2023-09-14 15:42 UTC, chabad360 commented
Is there a way to better indicate that it's an intermediate image (other than `<none>:<none>`)? Perhaps with it being greyed out, or being a thinner item? Or maybe hiding it behind the parent images somehow?

I would think the desire to delete those comes from the fact that it doesn't look like it's there for any reason other than to take up space. So providing a better indicator that they can't/shouldn't be deleted would likely avoid this issue entirely.

2023-09-15 10:23 UTC, jelly commented
> Is there a way to better indicate that it's an intermediate image/undelete-able(other than `<none>:<none>`)? Perhaps with it being greyed out, or being a thinner item? Or maybe hiding it behind the parent images somehow?

It is already hidden by default (under `show intermediate images`)

> I would think the desire to delete those comes from the fact that it doesn't look like it's there for any reason other than to take up space. So providing a better indicator that they can't/shouldn't be deleted would likely avoid this issue entirely.

We do show that they are used by running containers? Maybe it can show that it's a child of X.

2023-10-18 06:35 UTC, subhoghoshX commented
Fixed the error! It was just trying to get the name for ForceRemoveModal out of a `null` value. I ended up overthinking things for no reason.

The dialog for Remove and Force Remove indeed looks a bit empty, both the title (as there's no tags) and body.

![image](https://github.com/cockpit-project/cockpit-podman/assets/108616679/f4f69376-2dfd-4ca0-934e-f7a4e94cf84f)

![image](https://github.com/cockpit-project/cockpit-podman/assets/108616679/5c984d0b-45ab-497d-90fb-daa924fbb85c)

The format of the title is changed a little in #1451, I should land that first...

2023-11-13 08:07 UTC, martinpitt reviewed
Thanks! LGTM, but I'll leave the last word to @jelly

2023-11-13 10:26 UTC, jelly commented
> Thanks! LGTM, but I'll leave the last word to @jelly

I was under the impression that we should first land https://github.com/cockpit-project/cockpit-podman/pull/1451

2023-11-16 09:55 UTC, jelly commented
So I thought we should show something more then this for an intermediate image? Should we change it to delete intermediate image?

![image](https://github.com/cockpit-project/cockpit-podman/assets/67428/249b5025-19dc-4d02-8474-f84a008bca18)

This is the same behavior as normal images so this is acceptable. I wonder if we should warn upfront however as we know if it's un use.
![image](https://github.com/cockpit-project/cockpit-podman/assets/67428/148ea8db-e12b-4013-bc7a-0824941021c2)

2023-11-16 10:10 UTC, jelly requested changes

2023-11-16 10:10 UTC, jelly commented on test/check-application
> +        b.wait_not_in_text("#containers-images", intermediate_image_sel)
NVM, we already do this!

2023-11-16 10:12 UTC, jelly commented on test/check-application
> +        b.wait_not_in_text("#containers-images", intermediate_image_sel)
We only don't test if one is in use and try deleting that one.

2023-11-16 10:14 UTC, subhoghoshX commented on test/check-application
> +        b.wait_not_in_text("#containers-images", intermediate_image_sel)
Yes that's my plan as well to create the image (and also a container for force delete), before I just didn't know how to create one in test :)

2023-11-16 10:31 UTC, subhoghoshX commented
@jelly Thanks for looking into it. So you meant something like this?

![image](https://github.com/cockpit-project/cockpit-podman/assets/108616679/572e2a85-b940-4c7c-9eff-3b21c6c5aacf)

This actually fixes an issue that I probably introduced in #1451, there is two spaces in "Delete  image?", because of the missing tag in between which would've been there otherwise.

There's also a extra space between "Delete ?"

![image](https://github.com/cockpit-project/cockpit-podman/assets/108616679/28dfbb5d-7cf3-48fc-803b-99058ddd8644)

2023-11-16 10:43 UTC, jelly commented
> @jelly Thanks for looking into it. So you meant something like this?
> 
> ![image](https://user-images.githubusercontent.com/108616679/283415054-572e2a85-b940-4c7c-9eff-3b21c6c5aacf.png)
> 
> This actually fixes an issue that I probably introduced in #1451, there is two spaces in "Delete image?", because of the missing tag in between which would've been there otherwise.
> 
> There's also a extra space between "Delete ?"
> 
> ![image](https://user-images.githubusercontent.com/108616679/283418694-28dfbb5d-7cf3-48fc-803b-99058ddd8644.png)

Good point, if you can fix that, it would be great! But that should show intermediate image as well right?

2023-11-19 17:41 UTC, subhoghoshX commented on src/ForceRemoveModal.jsx
> +const ForceRemoveModal = ({ name = "intermediate image", reason, handleForceRemove }) => {
I'm not sure whether I should translate it, it's used in `cockpit.format(_("Delete $0?"), name)` down below. It is automatically translated when used this way, right? I'm confused.

2023-11-19 17:42 UTC, subhoghoshX commented on src/ForceRemoveModal.jsx
> +const ForceRemoveModal = ({ name = "intermediate image", reason, handleForceRemove }) => {
I'm not sure whether I should translate it, it's used in `cockpit.format(_("Delete $0?"), name)` down below. It is automatically translated when used this way, right? I'm confused.

2023-11-19 17:42 UTC, subhoghoshX commented on src/ImageDeleteModal.jsx
> +    const imageName = repoTags[0]?.split(":")[0].split("/").at(-1) ?? "intermediate";
Same here.

2023-11-19 17:43 UTC, subhoghoshX commented
Oh it has conflicts! I'll fix it tomorrow.

2023-11-21 08:20 UTC, cockpituous commented on src/ImageDeleteModal.jsx
> +                        Dialogs.show(<ForceRemoveModal name={repoTags[0] ?? _("intermediate image")}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1406-20231121-080751-114b2988-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-11-21 08:47 UTC, jelly commented on src/ImageDeleteModal.jsx
> +                        Dialogs.show(<ForceRemoveModal name={repoTags[0] ?? _("intermediate image")}
Here we should already know about `isIntermediateImage` so I would prefer using that.

2023-11-21 08:54 UTC, jelly requested changes
small fixup, then it's good

2023-11-21 13:11 UTC, subhoghoshX commented
All green :rocket: for some reason the tests are failing locally with `TEST_SHOW_BROWSER=true`, but I trust the CI.

2023-11-21 13:24 UTC, jelly approved these changes

2023-11-21 13:28 UTC, jelly requested changes

2023-11-21 13:28 UTC, jelly commented on test/check-application
> +        self.confirm_modal("Force delete")
We don't confirm here if the image was gone and container was gone.

2023-11-21 14:51 UTC, jelly approved these changes
Thanks!

2023-11-21 15:03 UTC, merged