test: wait on new image tag
cockpit-project/cockpit-podman pull request #1907
Opened 2024-11-07 17:49 UTC by jelly

testDownloadImage flaked a very often as the test succeeds when runs fast enough. Tagging an image to a new name in this case changes the image list name to `copybox` possibly because it is sorted before `my-busybox`.

---

Alternatively we can wait on either?

2024-11-07 18:07 UTC, jelly commented
Ding ding ding, fails in some cases still so this needs to be conditional

2024-11-08 05:43 UTC, martinpitt requested changes
Ah, you are saying the "contains my-busybox" isn't specific enough? But the parent image shouldn't be shown in the "tr", just in the info below. :thinking: This smells funny, and also fails on some OSes. Let's figure out Monday.

2024-11-08 07:57 UTC, jelly commented
> Ah, you are saying the "contains my-busybox" isn't specific enough? But the parent image shouldn't be shown in the "tr", just in the info below. 🤔 This smells funny, and also fails on some OSes. Let's figure out Monday.

The image has two tags, but which one is shown is not predictable which is the issue shown in the failing tests. Either the UI does not update or it is unpredicable.

2024-11-11 14:50 UTC, jelly commented
Cool this works now

2024-11-11 15:15 UTC, martinpitt commented
[this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1907-ee681156-20241111-145135-rhel-9-6/log.html#39) looks like flake, /me leans on retry button

2024-11-11 15:17 UTC, martinpitt approved these changes
Ah, makes sense -- UI has the same order as .RepoTags

2024-11-11 15:48 UTC, jelly commented
> Ah, makes sense -- UI has the same order as .RepoTags

Yup, apparently that is not deterministic :D

2024-11-11 16:50 UTC, merged