Fix building PO template
cockpit-project/cockpit-podman pull request #551
Opened 2020-09-30 07:05 UTC by marusak

The current version failed with

    Option "--directory" requires 1 arguments, but 0 were provided

In the current stdio npm module version, getopt() now requires a
`default:` attribute, otherwise it considers the options as required.

Also sync PO helpers with current cockpit.

Cherry-picked from cockpit-project/starter-kit commit cbedf06

Checked and .pot file is built correctly. When we land this we need to retry #550

2020-09-30 07:37 UTC, martinpitt requested changes
Can you please also add this to travis, so that we don't fall into the same trap again? The original starter-kit commit does that.

2020-09-30 08:17 UTC, marusak commented
> Can you please also add this to travis, so that we don't fall into the same trap again?

done

2020-09-30 08:21 UTC, martinpitt commented
Sorry, I didn't realize that we don't have travis set up for c-podman. How about adding it to test/run instead?

2020-10-10 04:26 UTC, marusak commented
@Gundersanne can you please take a look? Thanks!

2020-10-10 09:23 UTC, Gundersanne approved these changes
lgtm :)

2020-10-10 10:10 UTC, merged