Revert "test: Explicitly install runc on Debian testing"
cockpit-project/cockpit-podman pull request #651
Opened 2021-01-12 21:48 UTC by skobyda

This reverts commit 03944ea904ab41282922c2260a5e3ee828e6fc89.

Since https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971253 has been
fixed, we can safely revert back to the 'crun'

Fixes a failure in https://github.com/cockpit-project/bots/pull/1531

2021-01-13 05:24 UTC, martinpitt commented
This is apparently not fixed in [ubuntu-stable](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-651-20210112-214843-3409cd89-ubuntu-stable/log.html) yet:
```
Error: default OCI runtime "runc" not found: invalid argument
Command '/var/tmp/vm.install' returned non-zero exit status 125.
```

Indeed [ubuntu groovy](https://launchpad.net/ubuntu/+source/libpod) still has podman 2.0.6, so I suggest to turn this into a condition on `if [ "${TEST_OS#ubuntu}" != "$TEST_OS" ]`.

2021-01-13 09:19 UTC, martinpitt requested changes
see above

2021-01-13 12:57 UTC, skobyda commented
> This is apparently not fixed in [ubuntu-stable](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-651-20210112-214843-3409cd89-ubuntu-stable/log.html) yet:
> 
> ```
> Error: default OCI runtime "runc" not found: invalid argument
> Command '/var/tmp/vm.install' returned non-zero exit status 125.
> ```
> 
> Indeed [ubuntu groovy](https://launchpad.net/ubuntu/+source/libpod) still has podman 2.0.6, so I suggest to turn this into a condition on `if [ "${TEST_OS#ubuntu}" != "$TEST_OS" ]`.

I'm not so profound in shell, what does '#ubuntu' do? just concatenate string? Then it could be just ubuntu-stable#ubuntu != ubuntu-stable ?

2021-01-13 13:35 UTC, martinpitt commented
@skobyda: See man bash "Parameter expansion". With `${var..}` you can manipulate strings. For example with `X=foo123.bar`, you can cut off a prefix, with `${X#foo} = "123.bar"`, or cut off a suffix with `${X%.bar} = "foo". This even works with `*` patterns, for example` ${X%.*} = "foo123"` (cut off a `.` and everything after it). These are the most common string operations, but you can e.g. also use default values if a variable is undefined (`${X:-defaultvalue}`) and others.

So `[ "${TEST_OS#ubuntu}" != "$TEST_OS" ]` is the POSIX shell way to ask "does the string `$TEST_OS` start with 'ubuntu'". If the string is different after cutting of an "ubuntu" prefix, then that is true. If it starts with anything else, the string does not have such a prefix, and `${TEST_OS#garbage}` = `$TEST_OS` (unchanged). Does that make sense?

It's similar to `echo "$TEST_OS" | grep -q '^ubuntu'`, except that it does not need two forks, an exec of grep, and grep's rather expensive string matching.

2021-01-14 01:57 UTC, skobyda commented
I see SRPM build failures (What does that mean)
Apart from that, both debian and ubuntu are now passing

2021-01-14 05:58 UTC, martinpitt approved these changes
Thanks! Not quibbling too much over style here, as this unblocks image refreshes.

Ignore the packit failures for now -- we can't fix them yet, but they are also something entirely new.

2021-01-14 05:58 UTC, martinpitt commented on test/vm.install
> +    OS_RELEASE=$(grep '^NAME' /etc/os-release | awk -F'=' '{print $2}')
OK for now, just a hint for the future: The canonical way to use that is to source it as a shell script:
```sh
. /etc/os-release
if [ "$NAME" = Ubuntu ] ...
```

2021-01-14 05:58 UTC, merged