WIP: Add always fetch latest version
cockpit-project/cockpit-podman pull request #859
Opened 2021-12-14 17:39 UTC by jelly

2022-01-03 10:52 UTC, marusak requested changes
Do we also test, that when you don't check in the new checkbox then it does not pull?

2022-01-03 10:52 UTC, marusak commented on test/check-application
> +        b.click("#run-image-dialog-pull-latest-image")
`b.set_checked("#run-image-dialog-pull-latest-image", True)`

2022-01-03 10:52 UTC, marusak commented on test/check-application
> +    @ testlib.skipImage("podman-restart not available in debian/ubuntu", *DISTROS_WITHOUT_PODMAN_RESTART)
Why these spaces in decorators?

2022-01-05 07:40 UTC, marusak approved these changes
Thanks!

2022-01-05 09:00 UTC, garrett commented
Initial reactions:

- There's not enough vertical space between the checkboxes. Is it using the correct elements? (Not saying space should be manually added... it's just weird that there isn't more. There should be, so this points to incorrect usage of elements... or a bug.)
- Start should be after pull, conceptually.

2022-01-05 09:24 UTC, garrett commented
So this is weird on a create dialog when there is no local image. Of course it'd pull the latest image, right? So then it's confusing why it's there.

I am pretty sure when we talked about this that it would probably only exist when there's an existing image and I think we talked about it showing up in the image section, under the image selector, and only when there's a match with a local image.

(Note: Between the holidays and currently being sick including a headache, I could be mistaken. But still, I think it's confusing when there's no local image, so I think this probably still needs work regardless of what we did or didn't talk about in the past.)

2022-01-07 09:41 UTC, jelly commented
> 

That's now implemented, not 100% sure if we discussed it before the implementation but it's certainly something which should be in the PR. Thanks for noticing!

2022-01-14 14:42 UTC, jelly commented
> So this is weird on a create dialog when there is no local image. Of course it'd pull the latest image, right? So then it's confusing why it's there.
> 
> I am pretty sure when we talked about this that it would probably only exist when there's an existing image and I think we talked about it showing up in the image section, under the image selector, and only when there's a match with a local image.

Moved the pull on create checkbox under the image select, but to avoid it from making the whole form jump it's always shown but only enabled for local images.

2022-01-17 09:05 UTC, garrett commented
> Moved the pull on create checkbox under the image select, but to avoid it from making the whole form jump it's always shown but only enabled for local images.

But we know when the image is being used in the image flow and should show it by default and when create container is selected, it's usually not going to be using a local image.

When we have some kind of "cloning" / "rebuild" option, it would also use a local image by default too.

Having a pull option always present even when it doesn't apply would be confusing.

(I'll look at this PR on my computer in a little bit. It's next in the queue now. :wink:)

2022-01-17 09:17 UTC, jelly commented
> > Moved the pull on create checkbox under the image select, but to avoid it from making the whole form jump it's always shown but only enabled for local images.
> 
> But we know when the image is being used in the image flow and should show it by default and when create container is selected, it's usually not going to be using a local image.

That's sort of true, if you create an image from a local container from the `Images` dialog sure it shouldn't be shown. But if you create it from the Containers dialog you can select local and remote images there I disabled it.

So, good point we should hide it when you create it from the `Images` section and keep it disabled/enabled for the `Containers` flow.

2022-01-17 12:38 UTC, garrett commented
> So, good point we should hide it when you create it from the Images section and keep it disabled/enabled for the Containers flow.

I was suggesting the opposite of that, actually. Show it for the images section (if there's a remote image available... that is, show it if it's not a locally created image) and don't show it by default for the create containers flow, unless it matches a local image in the selector.

2022-01-17 12:43 UTC, jelly commented
> > So, good point we should hide it when you create it from the Images section and keep it disabled/enabled for the Containers flow.
> 
> I was suggesting the opposite of that, actually. Show it for the images section (if there's a remote image available... that is, show it if it's not a locally created image) and don't show it by default for the create containers flow, unless it matches a local image in the selector.

Seems my brain mixed things up, sorry. We can do that, do we accept that the dialog will "jump" if you select a local image?

2022-01-17 13:13 UTC, garrett commented
> Seems my brain mixed things up, sorry. 

I'm grappling with a headache and feeling icky from being sick still (better, but still ugh)... so I'm just as likely to mix things up or suggest the wrong thing.

> We can do that, do we accept that the dialog will "jump" if you select a local image or can we keep some spacing so it doesn't occur.

We could have a statusline using a helpertext item there in place of a checkbox. ("The image will be downloaded from XYZ." or something like it could work... although it's probably redundant.) The helptertext widget, as it uses small text, might have a different line-height and we might need to adjust it to be the same height to not have a jump. But it'd be better than just a big gap there still... and this is a way to not have a jump.

...Or we just accept that the checkbox might jump into existence in some cases. We do have dialogs that change height already, as the result of interacting widgets above the content that changes.

2022-01-18 08:33 UTC, jelly commented
> > Seems my brain mixed things up, sorry.
> 
> I'm grappling with a headache and feeling icky from being sick still (better, but still ugh)... so I'm probably even more likely to mix things up or suggest the wrong thing or not be clear enough. wink
> 
> > We can do that, do we accept that the dialog will "jump" if you select a local image or can we keep some spacing so it doesn't occur.
> We could have a statusline using a helpertext item there in place of a checkbox. ("The image will be downloaded from XYZ." or something like it could work... although it's probably redundant.) The helptertext widget, as it uses small text, might have a different line-height and we might need to adjust it to be the same height to not have a jump. But it'd be better than just a big gap there still... and this is a way to not have a jump.

I think that adds to much redundant information, something which we should avoid.

> ...Or we just accept that the checkbox might jump into existence in some cases. We do have dialogs that change height already, as the result of interacting widgets above the content that changes.

That's the best compromise in my opinion, the new updated PR now shows it by default for the `Images` overview and it is shown when required for the "Create container" workflow under "Containers", the jumping seems acceptable and maybe something we can improve on later with new ideas.

2022-01-18 08:35 UTC, jelly commented
> Here's what the autocomplete is covering for me:
> 
> ![image](https://user-images.githubusercontent.com/10246/149790563-08868b4d-d0c6-4212-98a8-4c10738d3a77.png)
> 
> Additionally (out of scope of this PR): What is the `<none:none>`?

I have <none:none> too hmm, not sure where it comes from but it's also shown in `podman images`.

2022-01-19 08:38 UTC, marusak commented
`none:none` are intermediate images. We show them in the listing, but there is button on the bottom to show them.

2022-01-19 08:50 UTC, marusak requested changes
Looks good, thanks!
Can you please add test that we don't show this checkbox when pulling the image?

2022-01-19 10:45 UTC, jelly commented
> Looks good, thanks! Can you please add test that we don't show this checkbox when pulling the image?

added!

2022-01-19 10:59 UTC, marusak commented on test/check-application
> +        # testlib.sit()
:)

2022-01-19 12:00 UTC, marusak approved these changes
Awesome, thank you!
Can you please update screenshot as well for the release notes?

2022-01-19 12:24 UTC, jelly commented
> Awesome, thank you! Can you please update screenshot as well for the release notes?

done!

2022-01-21 07:49 UTC, merged