Create a container in a pod
cockpit-project/cockpit-podman pull request #867
Opened 2021-12-17 09:32 UTC by jelly

This adds the ability to create a new container in a pod group, a
container cannot be moved out or into a pod once it has been created.

Closes: #487

---

# Create container in pod

It is now possible to create a container in an existing pod using the `Create container in pod` button.

![image](https://user-images.githubusercontent.com/67428/146522432-50f533c3-9a6b-4da5-b95b-efa1e04e1029.png)

Create container dialog now shows in which pod the container is created

![image](https://user-images.githubusercontent.com/67428/146522493-c8f6e3c9-bfbd-4305-bd3a-e3aae461c848.png)

2021-12-17 10:36 UTC, jelly commented
Once everything is reviewed, I think it makes sense to add a pixel test for the creation modal and overview

2021-12-20 08:11 UTC, marusak requested changes
So I was somewhat confused when I open the dialog for the first time. I was expecting to see there select with available pods. When you would click on `Create container` it would not preselect any pod, but would be `No pod` or something like that. And if you would click on `Create container` in pod area, it would preselect that given one. (Note, that I don't like `Create container in pod` string, I would always just keep it `Create container`).
@jelly WDYT?

2021-12-20 09:25 UTC, jelly commented
> So I was somewhat confused when I open the dialog for the first time. I was expecting to see there select with available pods. When you would click on `Create container` it would not preselect any pod, but would be `No pod` or something like that. And if you would click on `Create container` in pod area, it would preselect that given one. (Note, that I don't like `Create container in pod` string, I would always just keep it `Create container`). @jelly WDYT?

In the discussion I had with Garrett, we concluded to not add another option to the already quite extensive options we have and instead change the title of the creation modal.

Can we do something to improve the button text maybe, "create a container in this pod?" It seems that the context for the button is not clear enough?

2021-12-20 18:13 UTC, marusak commented
> Can we do something to improve the button text maybe, "create a container in this pod?" It seems that the context for the button is not clear enough?

That is not an issue. I understand the difference between those buttons. I just thought that the workflow would be more clear with having the option, but if two of you agreed not to do it, then I am fine with it as well :)

2021-12-20 18:15 UTC, marusak approved these changes
Thanks!

2021-12-21 09:54 UTC, merged

2022-01-03 13:49 UTC, garrett commented
The status label is between actions:

![image](https://user-images.githubusercontent.com/67428/146522770-e06a8462-fae2-44a8-9fbf-d93ce0bec157.png)

This should be (running) [Create container in pod] ...

2022-01-04 12:35 UTC, marusak commented
@jelly can you please update here screenshot to accommodate change from #878 ? Thanks!