Move Owner option to Details tab
cockpit-project/cockpit-podman pull request #939
Opened 2022-03-09 13:04 UTC by jelly

Align the podman create image design with the in progress machines
dialog redesign. The owner option is now moved to the details tab and
changed to a radio button so it's more clear it's a form option. The
container name input can now take up the full input which is nicer on
mobile devices.

2022-03-09 15:13 UTC, garrett requested changes
It looks great!

There's an alignment issue, however:

![Screenshot from 2022-03-09 16-11-14](https://user-images.githubusercontent.com/10246/157470157-6a45b6d9-a14c-48a8-8829-e9652fe3f6d7.png)

2022-03-09 15:14 UTC, garrett commented
Oh, and it's called "Location" in Machines. Should it be the same here too? We should make the two consistent when it makes sense.

2022-03-09 15:34 UTC, garrett commented
Ahem...

![image](https://user-images.githubusercontent.com/10246/157474726-38b72684-8ef0-4e99-ab1d-52458aeafc22.png)

2022-03-14 09:06 UTC, jelly commented
> It looks great!
> 
> There's an alignment issue, however:
> 
> ![Screenshot from 2022-03-09 16-11-14](https://user-images.githubusercontent.com/10246/157470157-6a45b6d9-a14c-48a8-8829-e9652fe3f6d7.png)

That's missing `hasNoPaddingTop`, fixed.

2022-03-14 09:08 UTC, jelly commented
> Ahem... (Name entry appears _below_ its label.)
> 
> ![image](https://user-images.githubusercontent.com/10246/157474726-38b72684-8ef0-4e99-ab1d-52458aeafc22.png)

Is that on mobile? Firefox? Web?

2022-03-15 09:17 UTC, garrett commented
> Is that on mobile? Firefox? Web?

Firefox, just switched tabs to integration and this happened.

2022-03-15 09:56 UTC, garrett commented
So I have an idea and it seems to work...

Locally recreate `.pf-c-form__group.pf-m-horizontal`, but have it apply at the FormGroup level instead of Form.

```patch
diff --git src/ImageRunModal.jsx src/ImageRunModal.jsx
index e438f4a6..8a897145 100644
--- src/ImageRunModal.jsx
+++ src/ImageRunModal.jsx
@@ -810,8 +810,8 @@ export class ImageRunModal extends React.Component {
         );
 
         const defaultBody = (
-            <Form isHorizontal={activeTabKey == 0}>
-                <FormGroup fieldId='run-image-dialog-name' label={_("Name")}>
+            <Form>
+                <FormGroup fieldId='run-image-dialog-name' label={_("Name")} className="ct-m-horizontal">
                     <TextInput id='run-image-dialog-name'
                            className="image-name"
                            placeholder={_("Container name")}
diff --git src/ImageRunModal.scss src/ImageRunModal.scss
index 51fb65f6..ccde9424 100644
--- src/ImageRunModal.scss
+++ src/ImageRunModal.scss
@@ -1,3 +1,5 @@
+@import "global-variables";
+
 .dynamic-form-group {
     .pf-c-empty-state {
         padding: 0;
@@ -65,3 +67,13 @@
 .run-image-dialog-restart-retries {
     max-width: 5ch;
 }
+
+// HACK: A local copy of pf-m-horizontal (as ct-m-horizontal),
+// but applied at the FormGroup level instead of Form
+@media (min-width: $pf-global--breakpoint--md) {
+    .pf-c-form__group.ct-m-horizontal {
+        display: grid;
+        grid-column-gap: var(--pf-c-form--m-horizontal__group-label--md--GridColumnGap);
+        grid-template-columns: var(--pf-c-form--m-horizontal__group-label--md--GridColumnWidth) var(--pf-c-form--m-horizontal__group-control--md--GridColumnWidth);
+    }
+}
```

If you like this (ping me on IRC about it), I can push up my change.

2022-03-15 10:23 UTC, garrett approved these changes
Looks good after our changes.

2022-03-15 11:28 UTC, merged