Alternative to #930
cockpit-project/cockpit-podman pull request #942
Opened 2022-03-17 06:35 UTC by marusak

It behaves the same as #930 but does not look great:
![Screenshot from 2022-03-17 07-29-53](https://user-images.githubusercontent.com/12330670/158750457-5ed7d6d0-4c68-430d-962a-9805d2d22225.png)

@garrett mentioned that columns should  constrain to their content. Not sure how to do that. By any chance, do you know if we use this right-alight and constraining anywhere else when using ListingTable?

2022-03-17 07:00 UTC, marusak commented
The wrapping commit seems fine so I picked it into https://github.com/cockpit-project/cockpit-podman/pull/943 also bumped pkg/lib to bring in animations of new items and pull in https://github.com/cockpit-project/cockpit-podman/pull/930/commits/46e94f0de60d000480a9fb266ec39cc2c891a8fc from #930

2022-03-17 08:22 UTC, garrett requested changes
I have the CSS in the other PR constrained to the content. But there was no way to attach the CSS to the rows except by how I did it. (Using offset numbers is not a valid method, as that can easily change and doesn't explain what's going on. There needs to be a way to target the cells by the type.)

Additionally:

- Legacy tables have _some_ ways to control the text: https://www.patternfly.org/v4/components/table/react-legacy#controlling-text
- Composable tables seem to have noWrap as an option too? https://www.patternfly.org/v4/components/table/#composable-custom-row-wrapper-header-tooltips--popovers

But I don't think the PF React methods are suitable enough. 

Elsewhere in Cockpit, either we don't have such dense information or we add classes to the `th` and `td` elements and use CSS to specify the approximate sizes.

2023-04-06 09:31 UTC, garrett commented
Also related to alignment and displaying numbers: I also mentioned in https://github.com/cockpit-project/cockpit-podman/pull/930#issuecomment-1049043237 about fixing the rounding so it's not absurd like this. I opened an issue about this for Metrics, but it would be useful across all of Cockpit:

- https://github.com/cockpit-project/cockpit/issues/17769

I provided an example function in that issue that does the job. It handles floats. If we're just interested in whole, positive numbers, we could even simplify it down to `num ? Math.round(num) || 1 : 0` (but I think we want decimal places and probably want to display a `< ` too).

2023-04-06 09:46 UTC, KKoukiou commented
@marusak this can't be  solved like this unfortunately. It's quite more complicated this closing this PR as it's also quite state. 
We have https://github.com/cockpit-project/cockpit-podman/issues/597 to track.

2023-04-06 09:46 UTC, closed without merging