Makefile: run tests fully offline
cockpit-project/cockpit-podman pull request #948
Opened 2022-03-24 10:56 UTC by jelly

All our test images now pull the requires podman test images during
image creation.

2022-03-24 11:15 UTC, martinpitt commented
This requires a corresponding change in test/vm.install to not untag and re-pull the images. Essentially just dropping the `else` branch.

2022-03-24 13:50 UTC, jelly commented
> This requires a corresponding change in test/vm.install to not untag and re-pull the images. Essentially just dropping the `else` branch.

Yup, I forgot we had special fedora handling, this is now done. But requires image refreshes for rhel-9-0 and rhel-8-6

2022-03-25 09:49 UTC, martinpitt commented
Sad to see some [f34 regression](https://artifacts.dev.testing-farm.io/f1d0d253-4969-4722-9547-1f07983e369b/) -- but we don't actually support/release to F34 any more, so we could just disable that.

Otherwise, nice to see that this works everywhere now! :+1:

2022-03-25 09:49 UTC, martinpitt approved these changes

2022-03-25 10:14 UTC, martinpitt requested changes

2022-03-25 10:14 UTC, martinpitt commented on packit.yaml
> +      - fedora-36
Please also add `- fedora-development` to continue to cover Rawhide.

2022-03-25 10:17 UTC, martinpitt approved these changes
Thanks! (Please wait on green, obviously)

2022-03-25 11:02 UTC, merged