Volumes support
cockpit-project/cockpit-podman pull request #957
Opened 2022-04-12 07:21 UTC by strzinek

Basic support for Podman volumes management:
* Container details - Mounts
* Container details - ENV
* Volumes list
* Volume details
* Create and remove volume

2022-04-12 08:54 UTC, garrett requested changes
Nice! Thanks for the PR.

It's a great start and seems mostly implemented feature-wise, but it's currently incomplete and still needs a bit of work.

---

As-is, this doesn't fit the design of Cockpit Podman, as you flipped the order of images and containers. As containers are derived from images, the images need to be on top. Additionally, the containers list can get very long, so everything below it might not be seen. This is why the design has images at the top and is expandable (and collapsed by default).

(Design doc @ https://github.com/cockpit-project/cockpit/discussions/16059)

Here's what it looks like in the PR right now:

![Screenshot 2022-04-12 at 10-36-32 Podman containers - garrett@Bolt](https://user-images.githubusercontent.com/10246/162919374-37e35fa1-9bd0-4e48-8251-de8404e96a5d.png)

We might want to use side-by-side cards at the top, similar to Cockpit-Machines. In widescreen, they're side-by-side. When space is constrained, they wrap and stack. (This can be done with [PatternFly Flex](https://www.patternfly.org/v4/utilities/flex/) with breakpoints.):

![Screenshot 2022-04-12 at 10-51-00 Virtual Machines - garrett@Bolt](https://user-images.githubusercontent.com/10246/162921367-b660e001-5637-4a52-92d2-07659dacb6df.png)

![Screenshot 2022-04-12 at 10-51-16 Virtual Machines - garrett@Bolt](https://user-images.githubusercontent.com/10246/162921370-e9cb01f8-37fe-4780-818f-d7f0b379e32c.png)


---

While it works when maximized on a high-res screen and also collapses down on mobile, the list doesn't work in standard desktop sizes:

![Screenshot 2022-04-12 at 10-36-46 Podman containers - garrett@Bolt](https://user-images.githubusercontent.com/10246/162919377-3c252d9d-bfd7-475d-9df3-7af44b2d2857.png)

Here it is in huge, just for reference of others viewing the PR:

![Screenshot 2022-04-12 at 10-37-36 Podman containers - garrett@Bolt](https://user-images.githubusercontent.com/10246/162919383-918b7f71-1dab-47ea-bcd4-41808a430243.png)

---

Create volume says "Create container" and has tabs. (It's not obvious what this does. I guess it creates volumes in a standard location, mainly for use in containers later?)

It shouldn't have tabs.

![Screenshot 2022-04-12 at 10-37-05 Podman containers - garrett@Bolt](https://user-images.githubusercontent.com/10246/162919379-054e3362-fbd3-4472-b29f-3c39ab759d33.png)

I'm assuming you'll add various options as listed @ https://docs.podman.io/en/latest/markdown/podman-volume-create.1.html too? (This could be handled in follow-up PRs.)

---


Just as a point of reference, prune and delete are the only options at the moment:

![Screenshot 2022-04-12 at 10-38-37 Podman containers - garrett@Bolt](https://user-images.githubusercontent.com/10246/162919388-5f99b6a2-4fb7-47a7-b0a2-2cf2badd5a20.png)

![Screenshot 2022-04-12 at 10-38-45 Podman containers - garrett@Bolt](https://user-images.githubusercontent.com/10246/162919390-649ed4f4-4d75-4789-9885-07a3897d92db.png)

2022-04-12 11:07 UTC, strzinek commented
Thanks @garrett for your review, I'll incorporate your valid comments.

2022-04-20 15:50 UTC, jelly commented
As volumes allow for purning unused volumes, shouldn't we also show which volume is unused and used by a container similar to images?

2022-04-20 16:04 UTC, strzinek commented
I agree, @jelly, but there is no volume usage info present in API, unlike for images. API does not even return volume ID's, only names. List of unused volumes could be reconstructed by going through all the containers on client side, I think. Or is there any easier way?

2022-05-04 09:58 UTC, garrett commented
Volumes details are empty. Should there be anything there? If not, they shouldn't be expandable. And if there's only one tab of information, there shouldn't be a tab.

![Screenshot 2022-05-04 at 11-53-16 Podman containers - garrett@Bolt](https://user-images.githubusercontent.com/10246/166660216-8310c720-5337-4cb3-bbe9-0833d55c0215.png)

---

Also, PF Cards now have the ability to be expandable. Perhaps we should use this for both Images and Volumes. But we can address that in a follow-up. It's just something to keep in mind as it would impact the way volumes look on the page.

https://www.patternfly.org/v4/components/card#expandable
https://www.patternfly.org/v4/components/card/react-demos/#horizontal-card-grid

2024-01-25 09:53 UTC, marusak commented
@strzinek Hey! Seems this fall of our radar and now has conflicts. Is this still something you are interested in and able to adjust to currect podman?

2024-02-17 19:11 UTC, strzinek commented
> @strzinek Hey! Seems this fall of our radar and now has conflicts. Is this still something you are interested in and able to adjust to currect podman?

I resolved merge conflicts and removed changes to container details, as these have since been implemented by someone else.

TODO: write basic tests for volumes

2026-06-18 08:00 UTC, jelly commented
Work continued in https://github.com/cockpit-project/cockpit-podman/pull/1959

2026-06-18 08:00 UTC, closed without merging