Better pod management
cockpit-project/cockpit-podman pull request #961
Opened 2022-04-14 18:04 UTC by strzinek

- Allow to create new pods with port mappings - new kebab control on containers panel
- Show pod owner in listings - under pod name
- Correctly limit container ownership when creating container in existing pod - select owner according to pod and disable owner selection

2022-04-20 15:08 UTC, jelly requested changes
Thanks for the PR! This was something we wanted to add for a while!

@garrett as we have limited set of integrations, do we still want to have a tabbed layout?

![image](https://user-images.githubusercontent.com/67428/164260276-d4a6a7a6-d35d-42fa-a3f5-8ab9b6837dad.png)

I've noticed that pods also supports volumes/mounts so should we add that as well?

2022-04-20 19:46 UTC, strzinek commented on src/Containers.jsx
> +                          ]} />
I am planning to implement other functions later which could go to kebab menu, and which are available through the API, e.g. Prune unused pods, Play a kube YAML, ... And I think two buttons together with filters would not look good on narrow layouts too. What do you think?

2022-04-25 15:48 UTC, garrett commented on src/Containers.jsx
> +            ];
Port mappings an mounts are at the pod level, right? I thought I had a design for this somewhere. (But perhaps I'm thinking of something else...?)

I'll look around, but it's end of the day today, so please ping me if I forget and take a while to get back to this.

2022-04-25 16:16 UTC, garrett commented on src/Containers.jsx
> +            ];
I wasn't able to find what I was thinking of. Perhaps I have a pattern in mind that was in another mockup.

This means I'll need to mock up what I have in mind for Cockpit-Podman. :wink:

2022-04-25 16:16 UTC, garrett commented
> @garrett as we have limited set of integrations, do we still want to have a tabbed layout?

No, please drop the tabs from this modal dialog. Thanks!

2022-05-02 17:29 UTC, strzinek commented on src/PodCreateModal.jsx
> +    }
Removed

2022-05-02 17:29 UTC, strzinek commented on src/PodCreateModal.jsx
> +const PublishPort = ({ id, item, onChange, idx, removeitem, itemCount }) =>
Moved to separate files.

2022-05-02 17:32 UTC, strzinek commented on src/PodCreateModal.jsx
> +    }
Pod config parameters differ from container.

2022-05-02 17:38 UTC, strzinek commented
Tabs removed.

I also added volumes section, but found out that mounts wont get created for pod because of bug in Podman: https://github.com/containers/podman/issues/13548 . I am not able to verify it is fixed in 4.x version as I am on fedora 35 for now.

I would also add a new test for creating pod later on.

2022-05-12 20:27 UTC, strzinek commented
Now it is possible to choose if infra container is created. Also, infra containers are not hidden in pods listings anymore.

I also prepared two new tests, TestApplication.testCreatePodUser and TestApplication.testCreatePodSystem.

2022-05-18 16:49 UTC, jelly requested changes

2022-05-18 16:49 UTC, jelly commented on src/Containers.jsx
> +            ];
@garrett the pod details design is here https://github.com/cockpit-project/cockpit-podman/issues/489 but that does not deal with the owner field. Maybe we can improve this in a follow up PR.

2022-05-18 16:50 UTC, jelly commented
I think this is a good PR to look at landing next after the rename PR.

2022-05-19 19:27 UTC, strzinek commented on src/Containers.jsx
> -            filtered = filtered.filter(id => !this.props.containers[id].IsInfra);
Infra container is a placeholder for shared resources of pod containers. The pod port mapping for example is defined on it. Without showing infra container, user of cockpit-podman does not know if pod has such shared resources and what ports pod exposes.

2022-08-08 11:29 UTC, jelly commented
The rename PR, can you rebase the PR please?

2022-08-19 08:36 UTC, jelly commented
I've rebased the PR, resolved the conflicts and dropped some of the things which can be a follow up PR.

2022-08-22 06:41 UTC, marusak commented
This breaks pixel tests: https://cockpit-logs.us-east-1.linodeobjects.com/pull-961-20220819-084819-8540cbeb-fedora-35/TestApplication-testRunImageSystem-integration-pixels.png

It causes regression, I did this change a few weeks ago - wrong checkout?

Also needs some new tests

2022-08-22 08:59 UTC, jelly commented
> This breaks pixel tests: https://cockpit-logs.us-east-1.linodeobjects.com/pull-961-20220819-084819-8540cbeb-fedora-35/TestApplication-testRunImageSystem-integration-pixels.png
> 
> It causes regression, I did this change a few weeks ago - wrong checkout?
> 
> Also needs some new tests

Hmm the code was moved around so maybe it doesn't pick up some css changes?

2022-09-19 09:05 UTC, jelly commented
Failing tests on ubuntu-2204 are due to podman not support user mounts on 3.4.4 and requires 4.0.0 so our gui should hide it https://github.com/containers/podman/issues/10379

2022-09-27 10:02 UTC, jelly commented
Issue summary:

* Fedora-coreos/debian-testing testCreatePodUser fails for unknown reasons
* Changed Pixel tests for https://cockpit-logs.us-east-1.linodeobjects.com/pull-961-20220927-091133-81d25dcc-fedora-36/pixeldiff.html#TestApplication-testRunImageSystem-integration-medium
* Requires a new review

2022-09-29 14:22 UTC, marusak commented
Why `Owner` label is not on the same row?
![Screenshot from 2022-09-29 13-52-30](https://user-images.githubusercontent.com/12330670/193057106-24495a5c-6e86-411b-a878-d6986de8b932.png)

Like here for example?
![Screenshot from 2022-09-29 13-52-18](https://user-images.githubusercontent.com/12330670/193057244-dc74fb17-3ebf-413b-8a7a-89aefe5b433f.png)

Also found it a bit confusing, that when you create pod and give it ports and volumes, you don't see them in the UI unless you add there container and start it.

2022-09-29 16:00 UTC, jelly commented
> Also found it a bit confusing, that when you create pod and give it ports and volumes, you don't see them in the UI unless you add there container and start it.

Agreed, however.... the Ports can be found in `infraContainer` but for the mounts we need `infraContainerDetails` and that is only available when the pod is started. We should ask the podman guys to expose the mounts in the containers information to make this work nicely.

2022-10-03 08:49 UTC, marusak approved these changes
Superb, thank you!

2022-10-03 08:49 UTC, marusak commented
Can you please write proper release note with screenshot as well?

2022-10-03 08:49 UTC, marusak approved these changes

2022-10-03 08:50 UTC, merged

2022-10-03 15:40 UTC, strzinek commented
Thanks everyone for pushing things through, I haven't had any time to pursue this myself.

2022-10-04 07:23 UTC, jelly commented
> Thanks everyone for pushing things through, I haven't had any time to pursue this myself.

No problem, thanks for the initial PR!